name: CMake on multiple platforms
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        build_type: [Release]
        c_compiler: [gcc, cl]
        include:
          - os: windows-latest
            c_compiler: cl
            cpp_compiler: cl
            cmake_generator: ""
          - os: windows-latest
            c_compiler: gcc
            cpp_compiler: g++
            cmake_generator: "-G Ninja"
          - os: ubuntu-latest
            c_compiler: gcc
            cpp_compiler: g++
            cmake_generator: ""
        exclude:
          - os: ubuntu-latest
            c_compiler: cl
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install Ninja (Windows MinGW)
      if: matrix.os == 'windows-latest' && matrix.c_compiler == 'gcc'
      run: choco install ninja

    - name: Set up MinGW
      if: matrix.os == 'windows-latest' && matrix.c_compiler == 'gcc'
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        install: mingw-w64-x86_64-gcc mingw-w64-x86_64-ninja
        path-type: inherit

    - name: Set reusable strings
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

    - name: Configure CMake
      run: >
        cmake -B ${{ steps.strings.outputs.build-output-dir }}
        ${{ matrix.cmake_generator }}
        -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
        -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
        -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
        -S ${{ github.workspace }}

    - name: Build
      run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config ${{ matrix.build_type }}

    - name: Test
      working-directory: ${{ steps.strings.outputs.build-output-dir }}
      run: ctest --build-config ${{ matrix.build_type }}
